<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <title>See Battle</title>
    <link rel="stylesheet" href="../public/styles/main.css">
    <link rel="icon" href="../public/img/shipIcon.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script text="javascript" src="../public/scripts/jquery_min.js"></script>
    <script text="javascript" src="../public/scripts/main.js"></script>
</head>
<body>
    <div id="greet_container">
        <h1 style="color:#fff">Добро Пожаловать!</h1>
        <div id="main">
            <a href="/startGame">
                <button class="btn btn-primary go">В БОЙ!</button>
            </a>
        </div>
    </div>
</body>
</html>