<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="../styles/main.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script text="javascript" src="../scripts/jquery_min.js"></script>
  </head>
  <body>
    <div id="wrapper">
      <canvas id="canvasAI" width="400" height="400"></canvas>
      <canvas id="canvasUser" width="400" height="400"></canvas>
      <div id="userControls">
        <div id="messages" class="alert"></div>
        <div id="Userform">
        <form action="/createUserShips" method="POST" >
          <select id="typeOfShip">
            <option selected>Выберите тип корабля</option>
            <option name="coordsfourDeck">Четырехпалубный</option>
            <option name="coordsthreeDeck1">Трехпалубный 1</option>
            <option name="coordsthreeDeck2">Трехпалубный 2</option>
            <option name="coordstwoDeck1">Двухпалубный 1</option>
            <option name="coordstwoDeck2">Двухпалубный 2</option>
            <option name="coordstwoDeck3">Двухпалубный 3</option>
            <option name="coordsoneDeck1">Однопалубный 1</option>
            <option name="coordsoneDeck2">Однопалубный 2</option>
            <option name="coordsoneDeck3">Однопалубный 3</option>
            <option name="coordsoneDeck4">Однопалубный 4</option>
          </select>
          <div id="coordsfourDeck" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div class="points">
              <label class="labels">Третья палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div class="points">
              <label class="labels">Четвертая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsthreeDeck1" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="thirdPoint" class="points">
              <label class="labels">Третья палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsthreeDeck2" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="thirdPoint" class="points">
              <label class="labels">Третья палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordstwoDeck1" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordstwoDeck2" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordstwoDeck3" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsoneDeck1" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsoneDeck2" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsoneDeck3" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsoneDeck4" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
        </form>
        </div>
        <form>
          <input type="submit" disabled="disabled" value="Отправить корабли" id="sendShips">
        </form>
      </div>
    </div>
    
    

    <script text="javascript" src="../scripts/main.js"></script>
  </body>
</html>
