<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="../styles/main.css" />
    <script text="javascript" src="../scripts/jquery_min.js"></script>
  </head>
  <body>
    <canvas id="canvas" width="500" height="500"></canvas>
    <script text="javascript" src="../scripts/main.js"></script>
  </body>
</html>
