<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="../styles/main.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script text="javascript" src="../scripts/jquery_min.js"></script>
  </head>
  <body>
    <div id="wrapper">
      <canvas id="canvasAI" width="400" height="400"></canvas>
      <canvas id="canvasUser" width="400" height="400"></canvas>
      <div id="userControls">
        <div id="messages" class="alert"></div>
        <div id="Userform">
        <form action="/createUserShips" method="POST" >
          <select id="typeOfShip">
            <option selected>Выберите тип корабля</option>
            <option name="coordsfourdeck">Четырехпалубный</option>
            <option name="coordsthreedeck1">Трехпалубный 1</option>
            <option name="coordsthreedeck2">Трехпалубный 2</option>
            <option name="coordstwodeck1">Двухпалубный 1</option>
            <option name="coordstwodeck2">Двухпалубный 2</option>
            <option name="coordstwodeck3">Двухпалубный 3</option>
            <option name="coordsonedeck1">Однопалубный 1</option>
            <option name="coordsonedeck2">Однопалубный 2</option>
            <option name="coordsonedeck3">Однопалубный 3</option>
            <option name="coordsonedeck4">Однопалубный 4</option>
          </select>
          <div id="coordsfourdeck" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div class="points">
              <label class="labels">Третья палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div class="points">
              <label class="labels">Четвертая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsthreedeck1" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="thirdPoint" class="points">
              <label class="labels">Третья палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsthreedeck2" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="thirdPoint" class="points">
              <label class="labels">Третья палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordstwodeck1" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordstwodeck2" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordstwodeck3" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <div id="secondPoint" class="points">
              <label class="labels">Вторая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsonedeck1" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsonedeck2" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsonedeck3" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
          <div id="coordsonedeck4" class="coords">
            <div class="points">
              <label class="labels">Координаты</label>
              <span>Y</span>
              <span>X</span>
            </div>
            <div id="firstPoint" class="points">
              <label class="labels">Первая палуба</label>
              <input type="text" name="y" id="y">
              <input type="text" name="x" id="x">
            </div>
            <input type="submit" value="Разместить" class="submit">
          </div>
        </div>
        </form>
        <div id="shoot">
          <form id="shootForm" action="/usershooting" method="POST">
            <input type="text" name="y" id="targetY">
            <input type="text" name="x" id="targetX">
            <input type="submit" value="shoot" id="shootbtn">
          </form>
        </div>
        <div id="next">
          <form id="nextForm" action="/aishooting" method="POST">
            <input type="submit" value="ход компьютера" id="aishoot">
          </form>
        </div>
        <form>
          <input type="submit" disabled="disabled" value="Отправить корабли" id="sendShips">
        </form>
      </div>
    </div>
    <form action="createUserShips" method="POST">
      <input type="submit" value="fill" id="fillTheUserField">
    </form>
    

    <script text="javascript" src="../scripts/main.js"></script>
  </body>
</html>
